### ISSUE TITLE
question about " Kirchhoff’s Matrix-Tree Theorem".

### ISSUE THREAD

**Issue by yangxia605** [nanguoshun/LSR#10]
hello:
首先感谢您愿意分享代码并且有这么出色的工作。
我想请假一下， Kirchhoff’s Matrix-Tree Theorem在本文中的作用是什么呢？相比较不用这个矩阵树，直接构建图进行图卷积而言。
万分感谢！！！

**Comment by nanguoshun** [comment]
hi @yangxia605, we rely on the Matrix-tree theorem to learn the document-level structure. You may refer to the details in the model part.

**Comment by yangxia605** [comment]
好的，非常感谢您。
