### ISSUE TITLE
关于划分实体对跨句子的依据？

### ISSUE THREAD

**Issue by yangxia605** [nanguoshun/LSR#13]
您好：
论文中有讲到DOCRED数据集中存在45%的实体关系是跨句子，请问下您对于实体跨句子的划分是基于数据中的Evidence字段吗？
![image](https://user-images.githubusercontent.com/21167278/87287548-cefad780-c52c-11ea-9627-156446e40a55.png)
![image](https://user-images.githubusercontent.com/21167278/87287604-e043e400-c52c-11ea-8bc4-88e18034e901.png)
谢谢！！！

**Comment by nanguoshun** [comment]
@yangxia605 谢谢提问关注。是的，我们是参考这个这字段来区分Intra和Inter。

**Comment by VinnyHu** [comment]
> @yangxia605 谢谢提问关注。是的，我们是参考这个这字段来区分Intra和Inter。

您好，能不能将您计算intra和inter指标的函数也开源下，我最近用您的代码，然后自己模仿ign_f1的计算方式，写了个计算intra和inter的函数，但是在您的代码上面这两个值都远远的低于论文中的。
不胜感激，谢谢！
