### ISSUE TITLE
关于论文的一点疑惑

### ISSUE THREAD

**Issue by zyccyz** [nanguoshun/LSR#15]
GCN部分中的公式，为什么是u_i^{l-1}而不是u_j^{l-1}.
<img width="335" alt="gcn" src="https://user-images.githubusercontent.com/44648619/87434587-4019b800-c61d-11ea-96c2-ebde782391bf.png">

**Comment by nanguoshun** [comment]
@zyccyz 谢谢指正笔误，这是应该是u_j^{l-1}
