### ISSUE TITLE
about dis_h_2_t？

### ISSUE THREAD

**Issue by yangxia605** [nanguoshun/LSR#17]
hello@nanguoshun :
thanks for your excellent work!!!
I am confused about the value of dis_h_2_t?
And every mention will be the triple's head or tail,so every mention will Pairwise to tirple(h,t,r).
So how to calculate the distance between h_2_t? I have view the code , but not for the whole document distance. 
Thank you Soooo much!!!

**Comment by nanguoshun** [comment]
Hi @yangxia605 thanks for the question. We use DocRED's original code to compute the distance. The distance is mapped to 1~10 as indicated from line 111 to line 121 in the Config.py.  It is quite straightforward if you inspect the value step by step under debugging mode.

**Comment by yangxia605** [comment]
Thx for your patient explanation。
