### ISSUE TITLE
quetions about the structure induction part?

### ISSUE THREAD

**Issue by yangxia605** [nanguoshun/LSR#18]
Hi @nanguoshun 
有问题想要请教一下您：
问题在2.2.1:Structure Induction
（1）公示4，为什么需要求的每个节点成为 root？（这是Matrix-Tree这部分的原理吗？）我看这个原理是树的生成定理，那它是由树来推理（构建）图的吗？
（2）公示8，求的节点i和节点j之间的边缘概率，这个概率表示的实际含义是什么呢？
万分感谢您！！！

**Comment by nanguoshun** [comment]
Hi @yangxia605,谢谢提问。 （1）MTT可以用来生成non-projective dependency tree，tree包含root节点。  （2）边缘概率表示所有的non-projective dependency tree中边的概率之和。具体的理论可以参考：https://www.aclweb.org/anthology/D07-1015.pdf
