### ISSUE TITLE
About Equation (7) and Table 5

### ISSUE THREAD

**Issue by yangboye** [nanguoshun/LSR#19]
![Equation(7)](https://user-images.githubusercontent.com/38837030/88391218-57f6f600-cdec-11ea-8676-3dacd9107d8d.png)
- In Equation(7), $exp(s_{**i**}^{r}) if i=1$, it confused me, are there any typo? May be $exp(s_{**j**}^{r}) if i=1$?

- In Table 5, what do all these numbers in column 1 mean? e.g. `1 Refinement`; `2 Structure Induction`; `1 Multi-hop Reasoning`?

Thank you.

**Comment by yangboye** [comment]
And what is the function of s_i^r calculated by Equation (4)?

**Comment by nanguoshun** [comment]
hi @yangboye , thanks for your question.  1) For the equation 7, you could also refer to equation 14 of the paper: https://arxiv.org/pdf/1705.09207.pdf.   2) For the numbers in table 5,  here '-1 refinement' means the model performs less than 1 refinement compared with the full model.

**Comment by yangboye** [comment]
Thanks for your reply!
