### ISSUE TITLE
关于GPU的数量。

### ISSUE THREAD

**Issue by yangxia605** [nanguoshun/LSR#2]
您好：
首先，感谢您出色的工作并且分享代码。
请问一下您跑这个实验用了几块GPU呢？
感谢！

**Comment by nanguoshun** [comment]
@yangxia605 谢谢关注！Glove+LSR，BZ=20需要2个RTX2080 (2*11GB)，如果batchsize设置小的话，也可以在一个卡 (11G) 上跑

**Comment by qiunlp** [comment]
您好：没有GPU，如果不计较速度，是否也可以在CPU上跑？感谢！

**Comment by nanguoshun** [comment]
@qiunlp 不太建议用CPU跑，会非常慢，因为用GPU的话（Glove+LSR），Training大概需要8个小时

**Comment by nanguoshun** [comment]
I close this issue in case that there are no further new queries.
