### ISSUE TITLE
公式7和公式9

### ISSUE THREAD

**Issue by dover1** [nanguoshun/LSR#21]
你好，公式7的s和公式9的u的下标是不是有点问题？
![image](https://user-images.githubusercontent.com/46741404/88663535-5b50f100-d10e-11ea-9e55-2223de3e9ef8.png)
![image](https://user-images.githubusercontent.com/46741404/88663561-660b8600-d10e-11ea-8bd4-e847900b273b.png)

**Comment by nanguoshun** [comment]
hi @dover1 ，谢谢提问。公式7没问题，公式9应该是u_j，这儿是笔误，谢谢！
