### ISSUE TITLE
关于bert以及模型训练细节

### ISSUE THREAD

**Issue by slzbywdf** [nanguoshun/LSR#23]
您好，有两个问题想题问一下。BERT+LSR 的结果是仅使用bert-base跑出来的吗？ 然后模型训练的时候是只使用训练集进行训练吗？感谢您的回复，谢谢~

**Comment by nanguoshun** [comment]
hi @slzbywdf，谢谢关注。  1）是的，BERT+LSR是用BERT-Base跑出来的。 2）是的，我们只在Training  Set上进行训练。

谢谢！
