### ISSUE TITLE
Questions about Theta

### ISSUE THREAD

**Issue by ssppff** [nanguoshun/LSR#25]
Hello, thank you for sharing. What does Theta stand for in training? When I was doing my experiments, Theta was always high, up to 0.9, and I didn't change the Theta part of the code. How do you keep Theta stable during training? Thank you.

**Comment by nanguoshun** [comment]
hi @ssppff, thanks for your question. Theta here acts as a threshold. we directly use the code from the original repo  repohttps://github.com/thunlp/DocRED/blob/master/code/config/Config.py.
