### ISSUE TITLE
Running LSR on new dataset

### ISSUE THREAD

**Issue by nayakt** [nanguoshun/LSR#28]
Hi,

Can you please tell me the process to follow to run your model on a new dataset ? I can convert the data files in same format as train_annotated.json. What I want to know is which files are required in code/prepro_data directory and how to create them ?

Regards
Tapas

**Comment by nanguoshun** [comment]
Hi @nayakt , thanks for your attention. You need to refer to DoCRED: https://drive.google.com/drive/folders/1c5-0YwnoJx8NS6CV2f-NoTHR__BdkNqw  to prepare some files beforehand.

**Comment by nayakt** [comment]
Ok. Thanks !!!!
