### ISSUE TITLE
models

### ISSUE THREAD

**Issue by qiunlp** [nanguoshun/LSR#32]
您好！在学习您的代码，像gcn.py / class GraphConvLayer和attention.py /class SelfAttention这样的模块应该是套用典型的模块，我在网上找了很久，也没有发现有详细注释。请问你这些模块是从哪里来的？依据什么改编的？
谢谢！请原谅我的菜鸟问题。

**Comment by nanguoshun** [comment]
hi @qiunlp , thanks for your question.  For the GraphConvLayer, we refer to https://github.com/Cartus/AGGCN and https://github.com/qipeng/gcn-over-pruned-trees, two very nice implementations for relation extraction.

**Comment by qiunlp** [comment]
Thanks, I have read  https://github.com/Cartus/AGGCN
another?
两个，还有一个链接呢？您的2个链接一样
还有class SelfAttention参照哪里呀？
麻烦您了！

**Comment by nanguoshun** [comment]
Hi @qiunlp I have revised the second link.  For the SelAttention implementation, Please refer to the implementation in https://github.com/thunlp/DocRED/blob/master/code/models/ContextAware.py

**Comment by qiunlp** [comment]
Thank you very much.

非常感谢！
