### ISSUE TITLE
Some question about case study

### ISSUE THREAD

**Issue by Bosen-Zhang** [nanguoshun/LSR#5]
In the paper, you said that in the first refinement of LSR, Word War II interacts with several local mentions with higher attention scores, e.g., 0.43 for the mention Lake Force. But in the Figure 5, the score for the metion Lark Force is 0.30, the score for New Ireland is 0.43. Is there some error?

**Comment by Bosen-Zhang** [comment]
The deadline of EMNLP has come, I am looking forword that you can share the code as soon as possible, thank you

**Comment by nanguoshun** [comment]
Hi @Bosen-Zhang, this is a typo. Thanks for pointing out.  For the code, I am now cleaning it and will release it in early July.  Will keep you all informed. Thanks a lot!

**Comment by nanguoshun** [comment]
hi @Bosen-Zhang , we have released the code.  I close this issue in case there are no further queries. Thanks a lot!
