### ISSUE TITLE
Some question about the Intra-F1 and Inter-F1 test

### ISSUE THREAD

**Issue by xwjim** [nanguoshun/LSR#6]
In the paper,  it said that the intra-f1 and inter-f1 are computed based  on re-trained. How do you deal with the dataset when training intra-f1 and inter-f1. Whether you change the sents and vertexSet in the dataset

**Comment by nanguoshun** [comment]
hi @xwjim. We designed a rule to filter the intra- and inter-relation pairs. We didn't make any changes to the dataset. As indicated in our paper, an entity pair requires inter-sentence reasoning if the two entities from the same document have no mentions in the same sentence.

**Comment by xwjim** [comment]
> hi @xwjim. We designed a rule to filter the intra- and inter-relation pairs. We didn't make any changes to the dataset. As indicated in our paper, an entity pair requires inter-sentence reasoning if the two entities from the same document have no mentions in the same sentence.

Do you use the evience of the relational entity pair directly or classify by the mention position to classify the entity pairs for inter and intra

**Comment by nanguoshun** [comment]
To identity the inter and intra-relations, we refer to the evidence indices for each entity/mentions given in the "vertexSet" field of DoRED.

**Comment by nanguoshun** [comment]
I will close this issue if there are no further comments
